/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as NettoyageIleDeFranceRouteImport } from './routes/nettoyage-ile-de-france'
import { Route as NettoyagePantinRouteImport } from './routes/nettoyage-pantin'
import { Route as NettoyageParisRouteImport } from './routes/nettoyage-paris'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppPipelineRouteImport } from './routes/_authenticated/app.pipeline'
import { Route as AuthenticatedAppProspectionRouteImport } from './routes/_authenticated/app.prospection'
import { Route as AuthenticatedAppTarifsRouteImport } from './routes/_authenticated/app.tarifs'
import { Route as AuthenticatedAppDemandesIndexRouteImport } from './routes/_authenticated/app.demandes.index'
import { Route as AuthenticatedAppDemandesIdRouteImport } from './routes/_authenticated/app.demandes.$id'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const NettoyageIleDeFranceRoute = NettoyageIleDeFranceRouteImport.update({
  id: '/nettoyage-ile-de-france',
  path: '/nettoyage-ile-de-france',
  getParentRoute: () => rootRouteImport,
} as any)
const NettoyagePantinRoute = NettoyagePantinRouteImport.update({
  id: '/nettoyage-pantin',
  path: '/nettoyage-pantin',
  getParentRoute: () => rootRouteImport,
} as any)
const NettoyageParisRoute = NettoyageParisRouteImport.update({
  id: '/nettoyage-paris',
  path: '/nettoyage-paris',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPipelineRoute =
  AuthenticatedAppPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProspectionRoute =
  AuthenticatedAppProspectionRouteImport.update({
    id: '/prospection',
    path: '/prospection',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTarifsRoute = AuthenticatedAppTarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDemandesIndexRoute =
  AuthenticatedAppDemandesIndexRouteImport.update({
    id: '/demandes/',
    path: '/demandes/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDemandesIdRoute =
  AuthenticatedAppDemandesIdRouteImport.update({
    id: '/demandes/$id',
    path: '/demandes/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/merci': typeof MerciRoute
  '/nettoyage-ile-de-france': typeof NettoyageIleDeFranceRoute
  '/nettoyage-pantin': typeof NettoyagePantinRoute
  '/nettoyage-paris': typeof NettoyageParisRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/pipeline': typeof AuthenticatedAppPipelineRoute
  '/app/prospection': typeof AuthenticatedAppProspectionRoute
  '/app/tarifs': typeof AuthenticatedAppTarifsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/demandes/$id': typeof AuthenticatedAppDemandesIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/app/demandes/': typeof AuthenticatedAppDemandesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/merci': typeof MerciRoute
  '/nettoyage-ile-de-france': typeof NettoyageIleDeFranceRoute
  '/nettoyage-pantin': typeof NettoyagePantinRoute
  '/nettoyage-paris': typeof NettoyageParisRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/pipeline': typeof AuthenticatedAppPipelineRoute
  '/app/prospection': typeof AuthenticatedAppProspectionRoute
  '/app/tarifs': typeof AuthenticatedAppTarifsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/demandes/$id': typeof AuthenticatedAppDemandesIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/app/demandes': typeof AuthenticatedAppDemandesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/merci': typeof MerciRoute
  '/nettoyage-ile-de-france': typeof NettoyageIleDeFranceRoute
  '/nettoyage-pantin': typeof NettoyagePantinRoute
  '/nettoyage-paris': typeof NettoyageParisRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/pipeline': typeof AuthenticatedAppPipelineRoute
  '/_authenticated/app/prospection': typeof AuthenticatedAppProspectionRoute
  '/_authenticated/app/tarifs': typeof AuthenticatedAppTarifsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/demandes/$id': typeof AuthenticatedAppDemandesIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/app/demandes/': typeof AuthenticatedAppDemandesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/merci'
    | '/nettoyage-ile-de-france'
    | '/nettoyage-pantin'
    | '/nettoyage-paris'
    | '/reset-password'
    | '/app'
    | '/app/pipeline'
    | '/app/prospection'
    | '/app/tarifs'
    | '/app/'
    | '/app/demandes/$id'
    | '/lovable/email/transactional/preview'
    | '/app/demandes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/merci'
    | '/nettoyage-ile-de-france'
    | '/nettoyage-pantin'
    | '/nettoyage-paris'
    | '/reset-password'
    | '/app/pipeline'
    | '/app/prospection'
    | '/app/tarifs'
    | '/app'
    | '/app/demandes/$id'
    | '/lovable/email/transactional/preview'
    | '/app/demandes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/merci'
    | '/nettoyage-ile-de-france'
    | '/nettoyage-pantin'
    | '/nettoyage-paris'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/pipeline'
    | '/_authenticated/app/prospection'
    | '/_authenticated/app/tarifs'
    | '/_authenticated/app/'
    | '/_authenticated/app/demandes/$id'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/app/demandes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MerciRoute: typeof MerciRoute
  NettoyageIleDeFranceRoute: typeof NettoyageIleDeFranceRoute
  NettoyagePantinRoute: typeof NettoyagePantinRoute
  NettoyageParisRoute: typeof NettoyageParisRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-ile-de-france': {
      id: '/nettoyage-ile-de-france'
      path: '/nettoyage-ile-de-france'
      fullPath: '/nettoyage-ile-de-france'
      preLoaderRoute: typeof NettoyageIleDeFranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-pantin': {
      id: '/nettoyage-pantin'
      path: '/nettoyage-pantin'
      fullPath: '/nettoyage-pantin'
      preLoaderRoute: typeof NettoyagePantinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-paris': {
      id: '/nettoyage-paris'
      path: '/nettoyage-paris'
      fullPath: '/nettoyage-paris'
      preLoaderRoute: typeof NettoyageParisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pipeline': {
      id: '/_authenticated/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AuthenticatedAppPipelineRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/prospection': {
      id: '/_authenticated/app/prospection'
      path: '/prospection'
      fullPath: '/app/prospection'
      preLoaderRoute: typeof AuthenticatedAppProspectionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tarifs': {
      id: '/_authenticated/app/tarifs'
      path: '/tarifs'
      fullPath: '/app/tarifs'
      preLoaderRoute: typeof AuthenticatedAppTarifsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/demandes/': {
      id: '/_authenticated/app/demandes/'
      path: '/demandes'
      fullPath: '/app/demandes/'
      preLoaderRoute: typeof AuthenticatedAppDemandesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/demandes/$id': {
      id: '/_authenticated/app/demandes/$id'
      path: '/demandes/$id'
      fullPath: '/app/demandes/$id'
      preLoaderRoute: typeof AuthenticatedAppDemandesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppPipelineRoute: typeof AuthenticatedAppPipelineRoute
  AuthenticatedAppProspectionRoute: typeof AuthenticatedAppProspectionRoute
  AuthenticatedAppTarifsRoute: typeof AuthenticatedAppTarifsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppDemandesIdRoute: typeof AuthenticatedAppDemandesIdRoute
  AuthenticatedAppDemandesIndexRoute: typeof AuthenticatedAppDemandesIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppPipelineRoute: AuthenticatedAppPipelineRoute,
  AuthenticatedAppProspectionRoute: AuthenticatedAppProspectionRoute,
  AuthenticatedAppTarifsRoute: AuthenticatedAppTarifsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppDemandesIdRoute: AuthenticatedAppDemandesIdRoute,
  AuthenticatedAppDemandesIndexRoute: AuthenticatedAppDemandesIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MerciRoute: MerciRoute,
  NettoyageIleDeFranceRoute: NettoyageIleDeFranceRoute,
  NettoyagePantinRoute: NettoyagePantinRoute,
  NettoyageParisRoute: NettoyageParisRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
